### ISSUE TITLE
Add design document

### ISSUE THREAD

**Issue by richelbilderbeek** [programming-formalisms/programming_formalisms_example_project#1]
Should be easy, as @LarsEklund already prepared this at https://github.com/UPPMAX/programming_formalisms . I will just copy that file to README :-)

**Comment by richelbilderbeek** [comment]
Next step should be @LarsEklund's I think:

Hi Lars, 

I copied the design documents to this repo and linked to them in the README. Are you happy with this file structure? 

 * If yes, let me know and I will continue
 * If no, go ahead and change all at will :-)
 
 Thanks, Richel

**Comment by LarsEklund** [comment]
Perfect thank you @richelbilderbeek 
/Lars
