### ISSUE TITLE
Move design documents to `design` folder?

### ISSUE THREAD

**Issue by richelbilderbeek** [programming-formalisms/programming_formalisms_example_project#3]
Currently, the design documents are in the root folder. I suggest to move these to a folder called `design`.

What would @LarsEklund think about that? If he agrees, I'll happily do so :-)

**Comment by LarsEklund** [comment]
That is a good idea, please do that.

**Comment by richelbilderbeek** [comment]
Time to start working on this :-)

**Comment by richelbilderbeek** [comment]
Done!
